# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21513c913afd8b6b447ae04b810189b4e07fb18aae50c5cc3cb34a9572289679dcd09626442b7fa3a486857a12f484d4add46affe59d94e7178a06bfe1d35199

test:
  secret_key_base: 848f4696d519dc5b8a7d8bdcee5393b03985ea9cd0e1c9107142620ab4f0769d4fff19c5772a3cb04b7f891506b559ec43b28025a300011c25fb9b623074a53c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
